### ISSUE TITLE
Enable running without a message bus

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#285]

**Comment by callumforrester** [comment]
Blueapi can now tolerate a message bus connection failure on startup, but is not very usable. I've opened two separate tickets to fix that: #426 and #427.

I do still think this issue is valid as we want blueapi to be able to start up this way by design rather than just when the message bus fails, will post details below.

**Comment by callumforrester** [comment]
As a developer I want to configure the bluepai server and CLI to work without a message bus so that I can easily run it up without messing around with external dependencies. 

## Possible Solution
The way I suggest to do this is make `StompConfig` in `config.py` an optional part of `ApplicationConfig` and run mypy. It will highlight where the stomp config is being used on the assumption that it is definitely there and where None-checks are needed. Ultimately stomp can be made optional.

## Acceptance Criteria
- If a user does not supply a stomp config in the config file, blueapi server does not attempt to connect to a message bus on startup 
- If a user does not supply a stomp config in the config file, blueapi client does not attempt to connect to a message bus on running a plan
- There are tests that prove both paths
