### ISSUE TITLE
Add an endpoint to give all the plans where a given device is featured

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#528]
This plan discovery functionality would make writing plans easier.

As a user knowing that I need to use device X in my experiment I can query for a list of plans that use that device so that I can write that plan more easily.

Note: code editor might already be doing this better

**Comment by callumforrester** [comment]
> This plan discovery functionality would make writing plans easier

Not actually sure of a specific use case?

I suggest writing this in a "as a _ I would like to _ so that _" style

**Comment by DiamondJoseph** [comment]
As a beamline user, I would like to find all plans in which my device can be used, so that I can more easily find relevant plans to my use case

e.g. finding all plans that allow using a Linkam, to find temperature related plans
Alternative solution is allowing tagging plans and allowing searching based on tags

**Comment by stan-dot** [comment]
closing as not planned, this will be supported in the code-server editor far more easily
