### ISSUE TITLE
`kill -9` doesn't kill the subprocess 

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#561]
Running `kill <blueapi process id>` kills blueapi and the worker subprocess. `kill -9` leaves the subprocess orphaned and still running.

**Comment by joeshannon** [comment]
There is an `initalizer` on the `Pool` which has 
```python
# Replace sigint to allow subprocess to be terminated
signal.signal(signal.SIGINT, signal.SIG_IGN)
```
So probably could add an equivalent for `SIGKILL`.

**Comment by joeshannon** [comment]
Actually this is not the case as there is no way for a process to handle `SIGKILL` (see `man 7 signal`) : 

> The signals SIGKILL and SIGSTOP cannot be caught, blocked, or ignored.

I think this report came from MX, possibly @noemifrisina? Are you able to provide any more context on why SIGKILL is required instead of SIGINT (CTRL-C)?

The subprocess is created in the same process group as the parent, an alterative command would be to send the signal to all process in the process group e.g. 
```bash
kill -9 -1234 # Send to process group 1234
# or 
killall -9 -G blueapi # wiil only work if started with bluepi directly as killall matches command name
```
This command is also quite useful to see process tree and process group etc. `ps efo pid,ppid,pgid,comm`
