### ISSUE TITLE
Speedup github actions

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#629]
They take a long time and if we do some smart caching we could speed this up, freeing up resources.

Resources on that caching
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows
- https://www.warpbuild.com/blog/github-actions-speeding-up
- https://jcdan3.medium.com/4-ways-to-speed-up-your-github-action-workflows-a0b08067a6c6

**Comment by gilesknap** [comment]
I have used caching for container builds and it can be very effective. Sometimes 20 minute container builds are reduced to 1 minute.
https://github.com/epics-containers/ioc-adsimdetector/blob/574642e3eb8e6e24d6faca0a427f6b0a854a3bbb/.github/workflows/build.yml#L59-L60
I find there is a some overhead in cache read/write so that for smaller builds this becomes wasteful.

**Comment by stan-dot** [comment]
thanks, I'll look into it

**Comment by stan-dot** [comment]
it would be cool if we could run those actions locally...
https://github.com/nektos/act

**Comment by stan-dot** [comment]
this might be revisited in the future, not needed for now
