### ISSUE TITLE
Handle correlation IDs

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#96]
Requests may come in with correlation IDs. If they do not, we should generate them.

**Comment by callumforrester** [comment]
@keithralphs or @DiamondJoseph  is this issue still relevant or is there a telemetry issue to supersede it?

**Comment by keithralphs** [comment]
I think the telemetry stuff will encompass this, though there may be some nuance as to how exactly we want to do it, so I would keep this here for now until we've fully worked that out. My plan is to get Joe to apply Otel to his newly subprocessed BlueAPI so we'll prorbably address it then.

**Comment by stan-dot** [comment]
what is the further use of this correlation? the term implies some other related data structure but it is not clear what that is

**Comment by stan-dot** [comment]
Isn't it better if we just always add it ourselves, at the first injection - such as the first blueapi request? 

why would we ever rely on the user to generate them? @callumforrester

**Comment by DiamondJoseph** [comment]
"the gateway to the services" is "us" and is the entrypoint to the system for a user request.

**Comment by DiamondJoseph** [comment]
Ah see what you mean.

>Requests may come in with correlation IDs. If they do not, we should generate them.

Requests will eventually come from a service gateway that will inject the correlation id, which should then be propagated through outward requests/emitted documents. For now, since the gateway is still being created, if the request has one (e.g. it's been generated in GDA to trace/debug requests from that client) we propagate it, else we create it.

**Comment by callumforrester** [comment]
Now done by @keithralphs tracing changes
